Repository openshift/jenkins-client-plugin, pull requests merged in 2018-09, with the labels that each got.

#175 add image mirror documentation
  README.md
Labels: approved, lgtm, size/S

#179 add selector exists() example
  README.md
Labels: approved, lgtm, size/S

#176 Running `oc` with Proc to avoid command expansion
  pom.xml
  src/main/java/com/openshift/jenkins/plugins/pipeline/OcAction.java
  src/main/java/com/openshift/jenkins/plugins/pipeline/OcWatch.java
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandRunner.java
  src/main/java/com/openshift/jenkins/plugins/util/QuietTaskListenerFactory.java
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, lgtm, size/XL

#182 Fix env propagation
  src/main/java/com/openshift/jenkins/plugins/pipeline/OcAction.java
  src/main/java/com/openshift/jenkins/plugins/pipeline/OcWatch.java
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandRunner.java
Labels: approved, lgtm, size/L
