Repository openshift/jenkins-client-plugin, pull requests merged in 2018-04, with the labels that each got.

#134 fix namespace, creating single obj in list (more groovy obscurity)
  examples/jenkins-image-sample.groovy
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, lgtm, size/M

#136 enable several recent additions to ext test case, image now updated
  examples/jenkins-image-sample.groovy
Labels: approved, lgtm, size/S

#142 adding docs to verify a deployment
  README.md
Labels: approved, lgtm, size/S

#138 redo multi project fix to punt objectList<->projectList correlation, …
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, lgtm, size/L

#143 Fix copy paste issue
  README.md
Labels: approved, lgtm, size/S

#139 fix openshift.delete so that it can handle a selector groovy map and …
  examples/jenkins-image-sample.groovy
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
  src/main/resources/com/openshift/jenkins/plugins/pipeline/OpenShiftGlobalVariable/help.jelly
Labels: approved, lgtm, size/M

#146 update readme with watch restriction
  README.md
Labels: approved, lgtm, size/XS

#147 expose oc expose
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
  src/main/resources/com/openshift/jenkins/plugins/pipeline/OpenShiftGlobalVariable/help.jelly
Labels: approved, lgtm, size/XS

#148 adjust to the metadata.kind on returned objects having values like de…
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, size/XS

#150 fix multi namespace on new -o=name output
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, size/S
