Repository openshift/jenkins-client-plugin, pull requests merged in 2018-10, with the labels that each got.

#185 add test for unquoted template params with spaces
  examples/jenkins-image-sample.groovy
Labels: approved, lgtm, size/XS

#187 revert latest template param test; something is up with the jenkins i…
  examples/jenkins-image-sample.groovy
Labels: approved, size/XS

#186 handle multiple -p settings, with some of them having spaces, in a si…
  examples/issue184-template.yml
  examples/jenkins-image-sample.groovy
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java
Labels: approved, lgtm, size/L

#188 add verify service functionality provided by old plugin
  README.md
  examples/jenkins-image-sample.groovy
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
  src/main/resources/com/openshift/jenkins/plugins/pipeline/OpenShiftGlobalVariable/help.jelly
Labels: approved, lgtm, size/M

#189 enable OcAction --follow support
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, lgtm, size/M

#192 do not create executor pool on each command execution
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandRunner.java
Labels: approved, lgtm, size/S

#197 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#198 version lock the template being used
  examples/jenkins-image-sample.groovy
Labels: approved, lgtm, size/XS
