Repository openshift/jenkins-client-plugin, pull requests merged in 2018-03, with the labels that each got.

#126 Bootsrap an OWNERS file
  OWNERS
Labels: lgtm, size/XS

#125 Added add and remove methods to descriptor to allow easier groovy config
  README.md
  examples/configure-jenkins-client.groovy
  src/main/java/com/openshift/jenkins/plugins/OpenShift.java
Labels: approved, lgtm, size/M

#113 need to account for multiple projects, or projects outside the scoped…
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, lgtm, size/L

#129 add retry to RolloutManager
  examples/jenkins-image-sample.groovy
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
  src/main/resources/com/openshift/jenkins/plugins/pipeline/OpenShiftGlobalVariable/help.jelly
Labels: needs-ok-to-test, size/XS

#132 properly handle emtpy selectors in withEach
  examples/jenkins-image-sample.groovy
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, lgtm, size/S
