Repository openshift/jenkins-client-plugin, pull requests merged in 2019-03, with the labels that each got.

#242 Bump version
  pom.xml
Labels: approved, lgtm, size/XS

#246 Add adambkaplan as approver
  OWNERS
Labels: approved, lgtm, size/XS

#247 Fix issues of FindOc
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java
  src/main/java/com/openshift/jenkins/plugins/util/FindOC.java
Labels: approved, lgtm, ok-to-test, size/M

#243 Porting the current process launching approach to ClientCommandRunner
  src/main/java/com/openshift/jenkins/plugins/pipeline/OcAction.java
  src/main/java/com/openshift/jenkins/plugins/pipeline/OcWatch.java
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandRunner.java
Labels: approved, lgtm, ok-to-test, size/L

#248 create groovy shim tmp files in workspace dir to facilitate file shar…
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, lgtm, size/XS

#249 Bump version
  pom.xml
Labels: approved, lgtm, size/XS

#250 create Dockerfile to enable prow based PR jobs against v4.x clusters
  Dockerfile
Labels: approved, lgtm, size/S
