Repository openshift/jenkins-client-plugin, pull requests merged in 2019-01, with the labels that each got.

#212 Setting credentials update in README
  README.md
Labels: approved, lgtm, size/S

#214 get back to essential pre 1.0.17 file processing for watch/action
  examples/multicontainer-pipieline.groovy
  src/main/java/com/openshift/jenkins/plugins/pipeline/OcAction.java
  src/main/java/com/openshift/jenkins/plugins/pipeline/OcWatch.java
Labels: approved, lgtm, size/L

#219 Bump version
  pom.xml
Labels: approved, lgtm

#220 add link to jenkins jira on declarative/globalvars
  README.md
Labels: approved, lgtm, size/XS
