Repository openshift/jenkins-client-plugin, pull requests merged in 2019-10, with the labels that each got.

#302 Add an example for using openshift.tag
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#304 Adds sbose78, akashshinde otaviof to approvers
  OWNERS
Labels: approved, lgtm, size/XS

#307 Reformat ClientCommandBuilder.java
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java
Labels: approved, lgtm, size/XL

#308 Fix 306 namespace not passed to raw command
  deploy.sh
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java
  src/main/resources/com/openshift/jenkins/plugins/OpenShiftDSL.groovy
Labels: approved, lgtm, size/L

#310 Add the team as reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#309 Universal redeploy script
  deploy.sh
Labels: approved, lgtm, size/XS
