Repository openshift/jenkins-client-plugin, pull requests merged in 2019-05, with the labels that each got.

#264 remove space param test again since we have 3.11 jenkins e2e working …
  examples/jenkins-image-sample.groovy
Labels: approved, lgtm, size/M

#265 removal of space param test removed too much
  examples/jenkins-image-sample.groovy
Labels: approved, lgtm, size/S

#267 travis/prow no longer copacetic
  .travis.yml
Labels: approved, lgtm, size/XS

#266 Enhance documentation
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#272 finally migrate fix oc path logging to verbose only
  src/main/java/com/openshift/jenkins/plugins/util/ClientCommandBuilder.java
Labels: approved, lgtm, size/XS
